retargeting:
  type: position
  urdf_path: xarm7/xarm7_ability_right_hand.urdf

  target_joint_names: ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6', 'joint7', 
                        'thumb_q1','index_q1', 'middle_q1', 'ring_q1', 'pinky_q1', 'thumb_q2']
  target_link_names: [ "thumb_tip",  "index_tip", "middle_tip", "ring_tip", "pinky_tip" ]

  target_link_human_indices: [ 4, 8, 12, 16, 20 ]
  add_dummy_free_joint:  False

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  # 1 means no filter while 0 means not moving
  low_pass_alpha: 0.9

  # To ignore the mimic joint tags in the URDF, set it to True
  ignore_mimic_joint: False
