retargeting:
  type: position
  urdf_path: xarm7/xarm7_allegro_right.urdf

  target_joint_names: null
  target_link_names: [ "link_15", "link_3", "link_7", "link_11", "link_14",
                       "link_2", "link_6", "link_10" ]

  target_link_human_indices: [ 4, 8, 12, 16, 2, 6, 10, 14 ]
  add_dummy_free_joint: False
  scaling_factor: 1.53

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  # 1 means no filter while 0 means not moving
  low_pass_alpha: 1
