retargeting:
  type: position
  urdf_path: xarm6/xarm6_allegro_right.urdf

  target_joint_names: null
  target_link_names: [ "link_15_tip", "link_3_tip", "link_7_tip", "link_11_tip", "link_14",
                       "link_2", "link_6", "link_10" ]

  target_link_human_indices: [ 4, 8, 12, 16, 2, 6, 10, 14 ]
  add_dummy_free_joint: False
  scaling_factor: 1.9

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  # 1 means no filter while 0 means not moving
  low_pass_alpha: 0.9
