retargeting:
  type: position
  urdf_path: ur5e/ur5e_shadow_right.urdf

  target_joint_names: null
  target_link_names: [ "palm","thtip", "fftip", "mftip", "rftip", "lftip",
                       "thmiddle", "ffmiddle", "mfmiddle", "rfmiddle", "lfmiddle"]

  target_link_human_indices: [ 0, 4, 8, 12, 16, 20, 2, 6, 10, 14, 18 ]
  add_dummy_free_joint: False
  scaling_factor: 1.35

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  # 1 means no filter while 0 means not moving
  low_pass_alpha: 0.8
