retargeting:
  type: position
  urdf_path: franka/panda.urdf

  target_joint_names: [ 'panda_joint1', 'panda_joint2', 'panda_joint3', 'panda_joint4', 'panda_joint5', 'panda_joint6', 'panda_joint7',"panda_finger_joint1" ]
  # target_link_names: [  "panda_left_hand","panda_leftfinger_pad", "panda_rightfinger_pad"]
  target_link_names: [  "panda_left_hand","panda_leftfinger_pad", "panda_rightfinger_pad","panda_leftfinger","panda_rightfinger"]

  target_link_human_indices: [ 0, 4, 8, 3, 6]
  add_dummy_free_joint: False

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  # 1 means no filter while 0 means not moving
  low_pass_alpha: 0.8

  scaling_factor: 0.9

  # To ignore the mimic joint tags in the URDF, set it to True
  ignore_mimic_joint: False
